### PR TITLE
Hamburger-menu

### PR DESCRIPTION
**Pull request by ScottyPoi**
re: #183 

Top Left Menu Icon now has content.

* Basic app manual
* What is Portal Network? q&a
* Links to implementations

### CODE REVIEW

**Comment by acolytec3** [comment]
I think the content is great in this but I don't love the presentation.  Not a UI expert but tapping the hamburger menu to get "More Info" feels counter-intuitive to me. The content feels really crowded in the drawer component so maybe put it in a modal that overlays the whole screen when you click on a "More Info" option.  I think my preference would be something like embed both the dev tools and the "More Info" buttons or links in a hamburger menu and then open a modal that fills the screen if/when you tap on it and then show this content.  I'll play around with it a little bit this morning and see what I come up with.

**Comment by acolytec3** [comment]
Here's what it looks like on mobile with my reworking.  It's not perfect but this feels a little more natural to me.  Thoughts?

Screenshot_20220412-092020_Ultralight
Screenshot_20220412-092016_Ultralight
Screenshot_20220412-092026_Ultralight

**Comment by acolytec3** [comment]
@ScottyPoi Take a peek at my changes and see what you think.  It probably bears further refinement but this feels maybe less busy on the main screen to me.  The menu is certainly busy but maybe good enough for now?  It also handles the starting the proxy on web (and only shows that startnode option if it detects we're on the web platform).

**Comment by ScottyPoi** [comment]
The only part that bugs me is that now you have to scroll to see everything in the menu, but i can live with that

**Pull request merged**
