### PR TITLE
Necessary changes to import a block from shandong testnet

### PR DESCRIPTION
**Pull request by acolytec3**
Hacked up changes to allow the CLI client to retrieve and serve blocks from Shandong testnet

Only works if you use `npm link` to link a local build of `@ethereumjs/common` as it leverages the currently unreleased `Common.fromGethGenesis` static constructor.

### CODE REVIEW

**Comment by holgerd77** [comment]
Ultralight <-> Shandong merger? How crazy is this! 🤯

**Comment by acolytec3** [comment]
I don't know that there's any actual value in this. I thought it was going to be easy and ended up spending 2 hours trying to make it work and it's all hacked together and definitely not something we want to merge right now 😬

**Comment by holgerd77** [comment]
> I don't know that there's any actual value in this. I thought it was going to be easy and ended up spending 2 hours trying to make it work and it's all hacked together and definitely not something we want to merge right now 😬

All fine. 😋 🙂

**Comment by acolytec3** [comment]
Shandong is deprecated so closing this.

**Pull request closed without merging**
